# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ec69035cd600d9045d3eda07db912a74d08c1a862b4a9ada420558aa6caf36a4a17a3baa56521405e413421fa1d5adffb0498f27d1072e4298416f9e838f81

test:
  secret_key_base: fe4bbb80d626e6abc7bdd284f69fba0e31cfc011fe86ee361a6189d9e7c75cae2d66856b8f38f47b26e479a8a81d44fdfa5e510364b8a630f04e95e9847c968e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
